apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: demok8s
  #
  # Annotate the service account with the Azure AD application which
  # has access our Blob store.
  #
  annotations:
    azure.workload.identity/client-id: cc312bc3-3859-42f1-9598-2371055dbfa4
    azure.workload.identity/tenant-id: 72f988bf-86f1-41af-91ab-2d7cd011db47
  labels:
    azure.workload.identity/use: "true"

# create namespace with kubectl create -f namespace.json
# create service account with: kubectl apply -f serviceaccount.yaml
